# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        pip install -r ./travis/lint-requirements.txt
    - name: Run lint
      run: |
        ./lint.sh


  python-small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        INSTALL_SMALL_PYTHON_DEPS=true source ./travis/install-common-deps.sh
    - name: Run tests
      run: |
        ./travis/run-small-python-tests.sh
        ./test-generate-protos.sh


  python-large:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        INSTALL_LARGE_PYTHON_DEPS=true source ./travis/install-common-deps.sh
    - name: Run tests
      run: |
        ./travis/run-large-python-tests.sh
        ./travis/test-anaconda-compatibility.sh "anaconda3:2020.02"
        ./travis/test-anaconda-compatibility.sh "anaconda3:2019.03"
